package rbmbfm.model.am;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import rbmbfm.model.am.common.BFMTransactionAM;
import rbmbfm.model.common.TransactionType;
import rbmbfm.model.vo.app.TransactionBaseVORowImpl;
import rbmbfm.model.vo.app.TransactionDetailVORowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 27 19:30:53 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BFMTransactionAMImpl extends ApplicationModuleImpl implements BFMTransactionAM {
    /**
     * This is the default constructor (do not remove).
     */
    public BFMTransactionAMImpl() {
    }

    /**
     * Container's getter for InwardLCTransactionDetailVO1.
     * @return InwardLCTransactionDetailVO1
     */
    public ViewObjectImpl getInwardLCTransactionDetailVO1() {
        return (ViewObjectImpl) findViewObject("InwardLCTransactionDetailVO1");
    }

    /**
     * Container's getter for SearchInwardLCTransactionDetailVO.
     * @return SearchInwardLCTransactionDetailVO
     */
    public ViewObjectImpl getSearchInwardLCTransactionDetailVO() {
        return (ViewObjectImpl) findViewObject("SearchInwardLCTransactionDetailVO");
    }

    /**
     * Container's getter for BankDetailVO.
     * @return BankDetailVO
     */
    public ViewObjectImpl getBankDetailVO() {
        return (ViewObjectImpl) findViewObject("BankDetailVO");
    }

    /**
     * Container's getter for InwardLCTransactionTypeVVO.
     * @return InwardLCTransactionTypeVVO
     */
    public ViewObjectImpl getInwardLCTransactionTypeVVO() {
        return (ViewObjectImpl) findViewObject("InwardLCTransactionTypeVVO");
    }

    /**
     * Container's getter for GetBeneficiaryDetailVO1.
     * @return GetBeneficiaryDetailVO1
     */
    public ViewObjectImpl getGetBeneficiaryDetailVO1() {
        return (ViewObjectImpl) findViewObject("GetBeneficiaryDetailVO1");
    }

    /**
     * Container's getter for InwardLCTransactionDetailVO2.
     * @return InwardLCTransactionDetailVO2
     */
    public ViewObjectImpl getInwardLCTransactionDetailVO2() {
        return (ViewObjectImpl) findViewObject("InwardLCTransactionDetailVO2");
    }

    /**
     * Container's getter for BankFacilityStructureVO1.
     * @return BankFacilityStructureVO1
     */
    public ViewObjectImpl getBankFacilityStructureVO1() {
        return (ViewObjectImpl) findViewObject("BankFacilityStructureVO1");
    }

    /**
     * Container's getter for InwardLCTransactionDetailVO3.
     * @return InwardLCTransactionDetailVO3
     */
    public ViewObjectImpl getInwardLCTransactionDetailVO3() {
        return (ViewObjectImpl) findViewObject("InwardLCTransactionDetailVO3");
    }

    /**
     * Container's getter for BankFacilityStructureVVO1.
     * @return BankFacilityStructureVVO1
     */
    public ViewObjectImpl getBankFacilityStructureVVO1() {
        return (ViewObjectImpl) findViewObject("BankFacilityStructureVVO1");
    }

    /**
     * Container's getter for FacilityAvailableLimitVO.
     * @return FacilityAvailableLimitVO
     */
    public ViewObjectImpl getFacilityAvailableLimitVO() {
        return (ViewObjectImpl) findViewObject("FacilityAvailableLimitVO");
    }

    /**
     * Container's getter for SearchTransactionDetailVO.
     * @return SearchTransactionDetailVO
     */
    public ViewObjectImpl getSearchTransactionDetailVO() {
        return (ViewObjectImpl) findViewObject("SearchTransactionDetailVO");
    }

    /**
     * Container's getter for TransactionBaseVO.
     * @return TransactionBaseVO
     */
    public ViewObjectImpl getTransactionBaseVO() {
        return (ViewObjectImpl) findViewObject("TransactionBaseVO");
    }

    /**
     * Container's getter for TransactionDetailVO.
     * @return TransactionDetailVO
     */
    public ViewObjectImpl getTransactionDetailVO() {
        return (ViewObjectImpl) findViewObject("TransactionDetailVO");
    }

    /**
     * Container's getter for TransactionDocumentRefVO.
     * @return TransactionDocumentRefVO
     */
    public ViewObjectImpl getTransactionDocumentRefVO() {
        return (ViewObjectImpl) findViewObject("TransactionDocumentRefVO");
    }

    /**
     * Container's getter for InwardLCToBeneficiaryDetailsVL1.
     * @return InwardLCToBeneficiaryDetailsVL1
     */
    public ViewLinkImpl getInwardLCToBeneficiaryDetailsVL1() {
        return (ViewLinkImpl) findViewLink("InwardLCToBeneficiaryDetailsVL1");
    }

    /**
     * Container's getter for LCTransactionDetailToBankFacilityStructureVL1.
     * @return LCTransactionDetailToBankFacilityStructureVL1
     */
    public ViewLinkImpl getLCTransactionDetailToBankFacilityStructureVL1() {
        return (ViewLinkImpl) findViewLink("LCTransactionDetailToBankFacilityStructureVL1");
    }

    /**
     * Container's getter for XxbfmTransactionDtlFk1Link1.
     * @return XxbfmTransactionDtlFk1Link1
     */
    public ViewLinkImpl getXxbfmTransactionDtlFk1Link1() {
        return (ViewLinkImpl) findViewLink("XxbfmTransactionDtlFk1Link1");
    }

    /**
     * Container's getter for XxbfmTransactionDocRefFk1Link1.
     * @return XxbfmTransactionDocRefFk1Link1
     */
    public ViewLinkImpl getXxbfmTransactionDocRefFk1Link1() {
        return (ViewLinkImpl) findViewLink("XxbfmTransactionDocRefFk1Link1");
    }

    /**
     * Container's getter for BfmMasterAM1.
     * @return BfmMasterAM1
     */
    public ApplicationModuleImpl getBfmMasterAM1() {
        return (ApplicationModuleImpl) findApplicationModule("BfmMasterAM1");
    }

    public void createTransaction(String type) {
        ViewObjectImpl transBaseVO = this.getTransactionBaseVO();
        TransactionBaseVORowImpl newRow = (TransactionBaseVORowImpl)transBaseVO.createRow();
        newRow.setAttribute("Type", type);

        transBaseVO.insertRow(newRow);
        
        BigDecimal transId = (BigDecimal)newRow.getAttribute("TransactionId");
        
        RowIterator transDetailIter = newRow.getTransactionDetailVO();
        TransactionDetailVORowImpl transDetailRow = (TransactionDetailVORowImpl)transDetailIter.createRow();
        transDetailRow.setAttribute("ApprovalStatus", TransactionType.DRAFT);
        transDetailIter.insertRow(transDetailRow);
        this.getDBTransaction().commit(); //Commit the changes
        transBaseVO.executeQuery();
    }
}

