package rbmbfm.model.vo.app;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;

import rbmbfm.model.eo.app.TransactionBaseEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 27 20:23:52 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransactionBaseVORowImpl extends ViewRowImpl {

    public static final int ENTITY_TRANSACTIONBASEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TransactionId,
        Type,
        TransactionNumber,
        Creator,
        Approver,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        Version,
        TenantId,
        TransactionDetailVO,
        TransactionDocumentRefVO,
        TransactionSourceDetailVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int TRANSACTIONID = AttributesEnum.TransactionId.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int TRANSACTIONNUMBER = AttributesEnum.TransactionNumber.index();
    public static final int CREATOR = AttributesEnum.Creator.index();
    public static final int APPROVER = AttributesEnum.Approver.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int TENANTID = AttributesEnum.TenantId.index();
    public static final int TRANSACTIONDETAILVO = AttributesEnum.TransactionDetailVO.index();
    public static final int TRANSACTIONDOCUMENTREFVO = AttributesEnum.TransactionDocumentRefVO.index();
    public static final int TRANSACTIONSOURCEDETAILVO = AttributesEnum.TransactionSourceDetailVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TransactionBaseVORowImpl() {
    }

    /**
     * Gets TransactionBaseEO entity object.
     * @return the TransactionBaseEO
     */
    public TransactionBaseEOImpl getTransactionBaseEO() {
        return (TransactionBaseEOImpl) getEntity(ENTITY_TRANSACTIONBASEEO);
    }

    /**
     * Gets the attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @return the TRANSACTION_ID
     */
    public BigDecimal getTransactionId() {
        return (BigDecimal) getAttributeInternal(TRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @param value value to set the TRANSACTION_ID
     */
    public void setTransactionId(BigDecimal value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_NUMBER using the alias name TransactionNumber.
     * @return the TRANSACTION_NUMBER
     */
    public String getTransactionNumber() {
        return (String) getAttributeInternal(TRANSACTIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_NUMBER using the alias name TransactionNumber.
     * @param value value to set the TRANSACTION_NUMBER
     */
    public void setTransactionNumber(String value) {
        setAttributeInternal(TRANSACTIONNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATOR using the alias name Creator.
     * @return the CREATOR
     */
    public String getCreator() {
        return (String) getAttributeInternal(CREATOR);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATOR using the alias name Creator.
     * @param value value to set the CREATOR
     */
    public void setCreator(String value) {
        setAttributeInternal(CREATOR, value);
    }

    /**
     * Gets the attribute value for APPROVER using the alias name Approver.
     * @return the APPROVER
     */
    public String getApprover() {
        return (String) getAttributeInternal(APPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER using the alias name Approver.
     * @param value value to set the APPROVER
     */
    public void setApprover(String value) {
        setAttributeInternal(APPROVER, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }

    /**
     * Gets the attribute value for TENANT_ID using the alias name TenantId.
     * @return the TENANT_ID
     */
    public BigDecimal getTenantId() {
        return (BigDecimal) getAttributeInternal(TENANTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TENANT_ID using the alias name TenantId.
     * @param value value to set the TENANT_ID
     */
    public void setTenantId(BigDecimal value) {
        setAttributeInternal(TENANTID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TransactionDetailVO.
     */
    public RowIterator getTransactionDetailVO() {
        return (RowIterator) getAttributeInternal(TRANSACTIONDETAILVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TransactionDocumentRefVO.
     */
    public RowIterator getTransactionDocumentRefVO() {
        return (RowIterator) getAttributeInternal(TRANSACTIONDOCUMENTREFVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TransactionSourceDetailVO.
     */
    public RowIterator getTransactionSourceDetailVO() {
        return (RowIterator) getAttributeInternal(TRANSACTIONSOURCEDETAILVO);
    }
}

