package rbmbfm.model.vo.app;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 27 20:29:00 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransactionDetailVORowImpl extends ViewRowImpl {


    public static final int ENTITY_TRANSACTIONDETAILEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TransactionDtlId,
        TransactionId,
        TransactionVersion,
        TransactionDate,
        BusinessEntityId,
        IssuingBankId,
        BeneficiaryBankId,
        FacilityTrackerId,
        ApprovalStatus,
        SourceType,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        Version,
        FacilityStructureId,
        TransactionValue,
        TransactionDocumentRefVO,
        BankFacilityStructureVO,
        TransactionSourceDetailVO,
        BusinessEntityVVO,
        BankFacilityStructureVVO,
        BeneficiaryBankVVO,
        IssuingBankVVO,
        SourceTypeVVO,
        CurrencyVVO,
        FacilityTrackerVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TRANSACTIONDTLID = AttributesEnum.TransactionDtlId.index();
    public static final int TRANSACTIONID = AttributesEnum.TransactionId.index();
    public static final int TRANSACTIONVERSION = AttributesEnum.TransactionVersion.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int BUSINESSENTITYID = AttributesEnum.BusinessEntityId.index();
    public static final int ISSUINGBANKID = AttributesEnum.IssuingBankId.index();
    public static final int BENEFICIARYBANKID = AttributesEnum.BeneficiaryBankId.index();
    public static final int FACILITYTRACKERID = AttributesEnum.FacilityTrackerId.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int SOURCETYPE = AttributesEnum.SourceType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int FACILITYSTRUCTUREID = AttributesEnum.FacilityStructureId.index();
    public static final int TRANSACTIONVALUE = AttributesEnum.TransactionValue.index();
    public static final int TRANSACTIONDOCUMENTREFVO = AttributesEnum.TransactionDocumentRefVO.index();
    public static final int BANKFACILITYSTRUCTUREVO = AttributesEnum.BankFacilityStructureVO.index();
    public static final int TRANSACTIONSOURCEDETAILVO = AttributesEnum.TransactionSourceDetailVO.index();
    public static final int BUSINESSENTITYVVO = AttributesEnum.BusinessEntityVVO.index();
    public static final int BANKFACILITYSTRUCTUREVVO = AttributesEnum.BankFacilityStructureVVO.index();
    public static final int BENEFICIARYBANKVVO = AttributesEnum.BeneficiaryBankVVO.index();
    public static final int ISSUINGBANKVVO = AttributesEnum.IssuingBankVVO.index();
    public static final int SOURCETYPEVVO = AttributesEnum.SourceTypeVVO.index();
    public static final int CURRENCYVVO = AttributesEnum.CurrencyVVO.index();
    public static final int FACILITYTRACKERVO = AttributesEnum.FacilityTrackerVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TransactionDetailVORowImpl() {
    }
}

