package rbmbfm.model.eo.app;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 15 08:55:04 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InwardLCTransactionDetailEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TransactionId,
        TransactionType,
        TransactionDate,
        TransactionNumber,
        SourceId,
        BusinessEntityId,
        IssuingBankId,
        FacilityTrackerId,
        ApprovalStatus,
        BeneficiaryBankId,
        SourceType,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        Version;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TRANSACTIONID = AttributesEnum.TransactionId.index();
    public static final int TRANSACTIONTYPE = AttributesEnum.TransactionType.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int TRANSACTIONNUMBER = AttributesEnum.TransactionNumber.index();
    public static final int SOURCEID = AttributesEnum.SourceId.index();
    public static final int BUSINESSENTITYID = AttributesEnum.BusinessEntityId.index();
    public static final int ISSUINGBANKID = AttributesEnum.IssuingBankId.index();
    public static final int FACILITYTRACKERID = AttributesEnum.FacilityTrackerId.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int BENEFICIARYBANKID = AttributesEnum.BeneficiaryBankId.index();
    public static final int SOURCETYPE = AttributesEnum.SourceType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InwardLCTransactionDetailEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("rbmbfm.model.eo.app.InwardLCTransactionDetailEO");
    }


    /**
     * Gets the attribute value for TransactionId, using the alias name TransactionId.
     * @return the value of TransactionId
     */
    public BigDecimal getTransactionId() {
        return (BigDecimal) getAttributeInternal(TRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionId.
     * @param value value to set the TransactionId
     */
    public void setTransactionId(BigDecimal value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for TransactionType, using the alias name TransactionType.
     * @return the value of TransactionType
     */
    public String getTransactionType() {
        return (String) getAttributeInternal(TRANSACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionType.
     * @param value value to set the TransactionType
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for TransactionDate, using the alias name TransactionDate.
     * @return the value of TransactionDate
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionDate.
     * @param value value to set the TransactionDate
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for TransactionNumber, using the alias name TransactionNumber.
     * @return the value of TransactionNumber
     */
    public String getTransactionNumber() {
        return (String) getAttributeInternal(TRANSACTIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionNumber.
     * @param value value to set the TransactionNumber
     */
    public void setTransactionNumber(String value) {
        setAttributeInternal(TRANSACTIONNUMBER, value);
    }

    /**
     * Gets the attribute value for SourceId, using the alias name SourceId.
     * @return the value of SourceId
     */
    public BigDecimal getSourceId() {
        return (BigDecimal) getAttributeInternal(SOURCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceId.
     * @param value value to set the SourceId
     */
    public void setSourceId(BigDecimal value) {
        setAttributeInternal(SOURCEID, value);
    }

    /**
     * Gets the attribute value for BusinessEntityId, using the alias name BusinessEntityId.
     * @return the value of BusinessEntityId
     */
    public BigDecimal getBusinessEntityId() {
        return (BigDecimal) getAttributeInternal(BUSINESSENTITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessEntityId.
     * @param value value to set the BusinessEntityId
     */
    public void setBusinessEntityId(BigDecimal value) {
        setAttributeInternal(BUSINESSENTITYID, value);
    }

    /**
     * Gets the attribute value for IssuingBankId, using the alias name IssuingBankId.
     * @return the value of IssuingBankId
     */
    public BigDecimal getIssuingBankId() {
        return (BigDecimal) getAttributeInternal(ISSUINGBANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssuingBankId.
     * @param value value to set the IssuingBankId
     */
    public void setIssuingBankId(BigDecimal value) {
        setAttributeInternal(ISSUINGBANKID, value);
    }

    /**
     * Gets the attribute value for FacilityTrackerId, using the alias name FacilityTrackerId.
     * @return the value of FacilityTrackerId
     */
    public BigDecimal getFacilityTrackerId() {
        return (BigDecimal) getAttributeInternal(FACILITYTRACKERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FacilityTrackerId.
     * @param value value to set the FacilityTrackerId
     */
    public void setFacilityTrackerId(BigDecimal value) {
        setAttributeInternal(FACILITYTRACKERID, value);
    }

    /**
     * Gets the attribute value for ApprovalStatus, using the alias name ApprovalStatus.
     * @return the value of ApprovalStatus
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalStatus.
     * @param value value to set the ApprovalStatus
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for BeneficiaryBankId, using the alias name BeneficiaryBankId.
     * @return the value of BeneficiaryBankId
     */
    public BigDecimal getBeneficiaryBankId() {
        return (BigDecimal) getAttributeInternal(BENEFICIARYBANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeneficiaryBankId.
     * @param value value to set the BeneficiaryBankId
     */
    public void setBeneficiaryBankId(BigDecimal value) {
        setAttributeInternal(BENEFICIARYBANKID, value);
    }

    /**
     * Gets the attribute value for SourceType, using the alias name SourceType.
     * @return the value of SourceType
     */
    public String getSourceType() {
        return (String) getAttributeInternal(SOURCETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceType.
     * @param value value to set the SourceType
     */
    public void setSourceType(String value) {
        setAttributeInternal(SOURCETYPE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the value of Version
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }


    /**
     * @param transactionId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal transactionId) {
        return new Key(new Object[] { transactionId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seqImpl = new SequenceImpl("XXBFM_INWARD_LC_TRANS_DTL_SEQ", this.getDBTransaction());
        BigDecimal seqBD = seqImpl.getSequenceNumber().getBigDecimalValue();
        setTransactionId(seqBD);
    }
}

