package rbmbfm.model.am.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 27 20:37:18 PDT 2015
// ---------------------------------------------------------------------
public interface BFMTransactionAM extends ApplicationModule {
    BigDecimal createTransaction(String type);

    void prepareTransactionDocumentHistoryVO();

    void setTransactionStatus(BigDecimal transactionDtlId, String status);

    BigDecimal copyToNewTransactionVersion(BigDecimal transactionDtlId);
}

