package rbmbfm.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 27 20:37:18 PDT 2015
// ---------------------------------------------------------------------
public interface BFMTransactionAM extends ApplicationModule {
    void createTransaction(String type);
}

