  INSERT INTO XXBFM.XXBFM_BANK_ALL(BANK_ID, BANK_SHORTNAME, BANK_NAME, BRANCH_ADDRESS, ACCOUNTNO, START_DATE, END_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN,TENANT_ID)
  VALUES(XXBFM_BANK_SEQ.NEXTVAL,'ICICI','ICICI BANK', 'S.R NAGAR, HYDERABAD','0101',TO_DATE('15-Nov-1980','dd-mon-yyyy'),TO_DATE('15-Nov-2020','dd-mon-yyyy'),'SYSADMIN',SYSDATE,'SYSADMIN',SYSDATE,'SYSADMIN',1);
    
  INSERT INTO XXBFM.XXBFM_BANK_ALL(BANK_ID, BANK_SHORTNAME, BANK_NAME, BRANCH_ADDRESS, ACCOUNTNO, START_DATE, END_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN,TENANT_ID)
  VALUES(XXBFM_BANK_SEQ.NEXTVAL,'HDFC','HDFC BANK', 'HITECH CITY, HYDERABAD','0102',TO_DATE('15-Nov-1980','dd-mon-yyyy'),TO_DATE('15-Nov-2020','dd-mon-yyyy'),'SYSADMIN',SYSDATE,'SYSADMIN',SYSDATE,'SYSADMIN',1);
  
  -----------------------
  INSERT INTO XXBFM.XXBFM_BUSINESS_ENTITY_ALL(BUSINESS_ENTITY_ID,BUSINESS_ENTITY, BUSINESS_GROUP,PROJECT_CODE,COMBINATION,STATUS)
  VALUES(XXBFM_BUSINESS_ENTITY_SEQ.NEXTVAL,'BBII','BANKING', 'LC','LC0102','ACTIV');

   ----------------------- 
  INSERT INTO XXBFM.XXBFM_FACILITY_STRUCTURE_ALL (FACILITY_STRUCTURE_ID,FACILITY_NAME)
  VALUES(XXBFM_FACILITY_STRUCTURE_SEQ.NEXTVAL,'ICICI CUSTOMER DIV.');
  -----------------------
  INSERT INTO  XXBFM.XXBFM_CURRENCY_ALL (CURRENCY_ID,CURRENCY_CODE,NAME,BASE_CURRENCY,CONVERSION_RATE,START_DATE,END_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,TENANT_ID)
  VALUES(XXBFM_CURRENCY_SEQ.NEXTVAL,'INR','Indian Rupee', 'INR','60',TO_DATE('15-Nov-1980','dd-mon-yyyy'),TO_DATE('15-Nov-2020','dd-mon-yyyy'),'SYSADMIN',SYSDATE,'SYSADMIN',SYSDATE,'SYSADMIN',1);
  
  --------------------------
  INSERT INTO XXBFM.XXBFM_FACILITY_TRACKER_ALL(FACILITY_TRACKER_ID,BANK_ID,BUSINESS_ENTITY_ID, FACILITY_STRUCTURE_ID,CURRENCY_ID,FACILITY_VALUE,BANK_REFERENCE)
  VALUES(XXBFM_FACILITY_TRACKER_SEQ.NEXTVAL,108,101,101, 101,1,'ICICI');

  --------------------------  
  
  --LOV--

INSERT
INTO XXBFM.XXBFM_LOOKUP_TYPE_ALL
  (
    LOOKUP_TYPE_ID,
    LOOKUP_TYPE,
    DESCRIPTION,
    START_DATE,
    END_DATE,
    STATUS,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TENANT_ID
  )
  VALUES
  (
    XXBFM_LOOKUP_TYPE_SEQ.NEXTVAL,
    'TRANSACTION_TYPE',
    'Transaction Type',
    TO_DATE('15-Nov-1980','dd-mon-yyyy'),
    TO_DATE('15-Nov-2020','dd-mon-yyyy'),
    'ACTIV',
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    1
  );
INSERT
INTO XXBFM.XXBFM_LOOKUP_VALUE_ALL
  (
    LOOKUP_VALUE_ID,
    LOOKUP_TYPE,
    LOOKUP_VALUE,
    DESCRIPTION,
    START_DATE,
    END_DATE,
    STATUS,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TENANT_ID
  )
  VALUES
  (
    XXBFM_LOOKUP_VALUE_SEQ.NEXTVAL,
    'TRANSACTION_TYPE',
    'Inward',
    'Inward LC Transaction',
    TO_DATE('15-Nov-1980','dd-mon-yyyy'),
    TO_DATE('15-Nov-2020','dd-mon-yyyy'),
    'ACTIV',
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    1
  );
INSERT
INTO XXBFM.XXBFM_LOOKUP_VALUE_ALL
  (
    LOOKUP_VALUE_ID,
    LOOKUP_TYPE,
    LOOKUP_VALUE,
    DESCRIPTION,
    START_DATE,
    END_DATE,
    STATUS,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TENANT_ID
  )
  VALUES
  (
    XXBFM_LOOKUP_VALUE_SEQ.NEXTVAL,
    'TRANSACTION_TYPE',
    'Outward',
    'Outward LC Transaction',
    TO_DATE('15-Nov-1980','dd-mon-yyyy'),
    TO_DATE('15-Nov-2020','dd-mon-yyyy'),
    'ACTIV',
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    1
  );  
  
-------  

INSERT
INTO XXBFM.XXBFM_LOOKUP_TYPE_ALL
  (
    LOOKUP_TYPE_ID,
    LOOKUP_TYPE,
    DESCRIPTION,
    START_DATE,
    END_DATE,
    STATUS,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TENANT_ID
  )
  VALUES
  (
    XXBFM_LOOKUP_TYPE_SEQ.NEXTVAL,
    'SOURCE_TYPE',
    'Source Type',
    TO_DATE('15-Nov-1980','dd-mon-yyyy'),
    TO_DATE('15-Nov-2020','dd-mon-yyyy'),
    'ACTIV',
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    1
  );
INSERT
INTO XXBFM.XXBFM_LOOKUP_VALUE_ALL
  (
    LOOKUP_VALUE_ID,
    LOOKUP_TYPE,
    LOOKUP_VALUE,
    DESCRIPTION,
    START_DATE,
    END_DATE,
    STATUS,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TENANT_ID
  )
  VALUES
  (
    XXBFM_LOOKUP_VALUE_SEQ.NEXTVAL,
    'SOURCE_TYPE',
    'Purchase Order',
    'Purchase Order',
    TO_DATE('15-Nov-1980','dd-mon-yyyy'),
    TO_DATE('15-Nov-2020','dd-mon-yyyy'),
    'ACTIV',
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    1
  );
INSERT
INTO XXBFM.XXBFM_LOOKUP_VALUE_ALL
  (
    LOOKUP_VALUE_ID,
    LOOKUP_TYPE,
    LOOKUP_VALUE,
    DESCRIPTION,
    START_DATE,
    END_DATE,
    STATUS,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    TENANT_ID
  )
  VALUES
  (
    XXBFM_LOOKUP_VALUE_SEQ.NEXTVAL,
    'SOURCE_TYPE',
    'Purchase Agreement',
    'Purchase Agreement',
    TO_DATE('15-Nov-1980','dd-mon-yyyy'),
    TO_DATE('15-Nov-2020','dd-mon-yyyy'),
    'ACTIV',
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    SYSDATE,
    'SYSADMIN',
    1
  );  
    
	
   insert into XXBFM_INWARD_LC_TXN_SOURCE (SOURCE_ID, PO_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, TENANT_ID)
   VALUES(10, 10, 'SYSADMIN', SYSDATE, 'SYSADMIN', SYSDATE, 'SYSADMIN', 1);	
   

   INSERT INTO XXBFM_BENEFICIARY_DETAIL (BENEFICIARY_ID, BENEFICIARY_NAME, CONTACT_NAME, CONTACT_NUMBER, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, TENANT_ID)
   values (1, 'James', 'James LLC', '101-223-2232','SYSADMIN', SYSDATE, 'SYSADMIN', SYSDATE, 'SYSADMIN', 1);
   
   INSERT INTO XXBFM_PURCHASE_ORDER (PO_ID, ORDER_NUMBER, DESCRIPTION_OF_GOODS, QUANTITY, UNIT_PRICE, CURRENCY_ID, TERMS_OF_DELIVERY, DUE_DATE, BENEFICIARY_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, TENANT_ID)
   VALUES (10, 'JEJ343434', 'WINDOWS 10', 10, 10.22, 101, 'Terms of delivery', TO_DATE('15-Nov-1980','dd-mon-yyyy'), 1, 'SYSADMIN', SYSDATE, 'SYSADMIN', SYSDATE, 'SYSADMIN', 1);
      