CREATE TABLE "XXBFM"."XXBFM_TRANSACTION_BASE"
  (
    "TRANSACTION_ID"     NUMBER NOT NULL ENABLE,
    "TYPE"               VARCHAR2(50 BYTE),
    "TRANSACTION_NUMBER" VARCHAR2(100 BYTE),
    "CREATOR"            VARCHAR2(100 BYTE),
    "APPROVER"           VARCHAR2(100 BYTE),
    "CREATED_BY"         VARCHAR2(256 BYTE) NOT NULL ENABLE,
    "CREATION_DATE"      TIMESTAMP (6) NOT NULL ENABLE,
    "LAST_UPDATED_BY"    VARCHAR2(256 BYTE) NOT NULL ENABLE,
    "LAST_UPDATE_DATE"   TIMESTAMP (6) NOT NULL ENABLE,
    "LAST_UPDATE_LOGIN"  VARCHAR2(32 BYTE),
    "VERSION"            NUMBER,
    "TENANT_ID"          NUMBER
  );

CREATE SEQUENCE XXBFM_TRANSACTION_BASE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
ALTER TABLE "XXBFM_TRANSACTION_BASE" ADD CONSTRAINT "XXBFM_TRANSACTION_BASE_PK" PRIMARY KEY ("TRANSACTION_ID") ENABLE;

  --------------------------
CREATE TABLE "XXBFM"."XXBFM_TRANSACTION_DTL"
  (
      "TRANSACTION_DTL_ID"  NUMBER,
      "TRANSACTION_ID"      NUMBER,
      "TRANSACTION_VERSION" NUMBER,
      "TRANSACTION_DATE"    DATE,
      "BUSINESS_ENTITY_ID"  NUMBER,
      "ISSUING_BANK_ID"     NUMBER,
      "BENEFICIARY_BANK_ID" NUMBER,
      "FACILITY_TRACKER_ID" NUMBER,
      "APPROVAL_STATUS"     VARCHAR2(50 BYTE) NOT NULL ENABLE,
      "SOURCE_TYPE"         VARCHAR2(100 BYTE),
      "CREATED_BY"          VARCHAR2(256 BYTE) NOT NULL ENABLE,
      "CREATION_DATE"       TIMESTAMP (6) NOT NULL ENABLE,
      "LAST_UPDATED_BY"     VARCHAR2(256 BYTE) NOT NULL ENABLE,
      "LAST_UPDATE_DATE"    TIMESTAMP (6) NOT NULL ENABLE,
      "LAST_UPDATE_LOGIN"   VARCHAR2(32 BYTE),
      "VERSION"             NUMBER
    );

CREATE SEQUENCE XXBFM_TRANSACTION_DTL_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
ALTER TABLE "XXBFM_TRANSACTION_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_DTL_PK" PRIMARY KEY ("TRANSACTION_DTL_ID") ENABLE;
ALTER TABLE "XXBFM_TRANSACTION_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_DTL_FK1" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "XXBFM"."XXBFM_TRANSACTION_BASE" ("TRANSACTION_ID") ENABLE;
ALTER TABLE "XXBFM_TRANSACTION_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_DTL_FK2" FOREIGN KEY ("BUSINESS_ENTITY_ID") REFERENCES "XXBFM"."XXBFM_BUSINESS_ENTITY_ALL" ("BUSINESS_ENTITY_ID") ENABLE;
ALTER TABLE "XXBFM_TRANSACTION_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_DTL_FK3" FOREIGN KEY ("ISSUING_BANK_ID") REFERENCES "XXBFM"."XXBFM_BANK_ALL" ("BANK_ID") ENABLE;
ALTER TABLE "XXBFM_TRANSACTION_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_DTL_FK4" FOREIGN KEY ("BENEFICIARY_BANK_ID") REFERENCES "XXBFM"."XXBFM_BANK_ALL" ("BANK_ID") ENABLE;
ALTER TABLE "XXBFM_TRANSACTION_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_DTL_FK5" FOREIGN KEY ("FACILITY_TRACKER_ID") REFERENCES "XXBFM"."XXBFM_FACILITY_TRACKER_ALL" ("FACILITY_TRACKER_ID") ENABLE;
  ------------------------------
CREATE TABLE "XXBFM"."XXBFM_TRANSACTION_DOC_REF"
   (
      "DOCUMENT_ID"        NUMBER,
      "TRANSACTION_DTL_ID" NUMBER,
      "TRANSACTION_ID"     NUMBER,
      "DOCUMENT_REF"       VARCHAR2(200 BYTE),
      "DOCUMENT_DATE"      DATE,
      "CURRENCY_ID"        NUMBER,
      "DOCUMENT_VAL"       NUMBER,
      "EXCHG_RATE"         NUMBER,
      "OTHER_REF"          VARCHAR2(200 BYTE),
      "CREATED_BY"         VARCHAR2(256 BYTE) NOT NULL ENABLE,
      "CREATION_DATE"      TIMESTAMP (6) NOT NULL ENABLE,
      "LAST_UPDATED_BY"    VARCHAR2(256 BYTE) NOT NULL ENABLE,
      "LAST_UPDATE_DATE"   TIMESTAMP (6) NOT NULL ENABLE,
      "LAST_UPDATE_LOGIN"  VARCHAR2(32 BYTE),
      "VERSION"            NUMBER,
      "TENANT_ID"          NUMBER
    );
CREATE SEQUENCE XXBFM_TRANSACTION_DOC_REF_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
ALTER TABLE "XXBFM_TRANSACTION_DOC_REF" ADD CONSTRAINT "XXBFM_TRANSACTION_DOC_REF_PK" PRIMARY KEY ("DOCUMENT_ID") ENABLE;
ALTER TABLE "XXBFM_TRANSACTION_DOC_REF" ADD CONSTRAINT "XXBFM_TRANSACTION_DOC_REF_FK1" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "XXBFM"."XXBFM_TRANSACTION_BASE" ("TRANSACTION_ID") ENABLE;
ALTER TABLE "XXBFM_TRANSACTION_DOC_REF" ADD CONSTRAINT "XXBFM_TRANSACTION_DOC_REF_FK2" FOREIGN KEY ("TRANSACTION_DTL_ID") REFERENCES "XXBFM"."XXBFM_TRANSACTION_DTL" ("TRANSACTION_DTL_ID") ENABLE; 


-----------------------------
CREATE TABLE "XXBFM"."XXBFM_TRANSACTION_SOURCE_DTL"
  (
    "SOURCE_ID"           NUMBER,
    "TRANSACTION_ID"      NUMBER,
    "BENEFICIARY_ID" NUMBER,
    "SOURCE_REF"          NUMBER,
    "SOURCE_DOC_DATE"     DATE,
    "SOURCE_CURRENCY"     NUMBER,
    "SOURCE_VAL"          NUMBER,
    "CREATED_BY"          VARCHAR2(256 BYTE) NOT NULL ENABLE,
    "CREATION_DATE"       TIMESTAMP (6) NOT NULL ENABLE,
    "LAST_UPDATED_BY"     VARCHAR2(256 BYTE) NOT NULL ENABLE,
    "LAST_UPDATE_DATE"    TIMESTAMP (6) NOT NULL ENABLE,
    "LAST_UPDATE_LOGIN"   VARCHAR2(32 BYTE),
    "VERSION"             NUMBER,
    "TENANT_ID"           NUMBER
  );
CREATE SEQUENCE XXBFM_TRANSACTION_SRC_DTL_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_TRANSACTION_SOURCE_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_SRC_DTL_PK" PRIMARY KEY ("SOURCE_ID") ENABLE;
  ALTER TABLE "XXBFM_TRANSACTION_SOURCE_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_SRC_DTL_FK1" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "XXBFM"."XXBFM_TRANSACTION_BASE" ("TRANSACTION_ID") ENABLE;
  ALTER TABLE "XXBFM_TRANSACTION_SOURCE_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_SRC_DTL_FK2" FOREIGN KEY ("BENEFICIARY_BANK_ID") REFERENCES "XXBFM"."XXBFM_BANK_ALL" ("BANK_ID") ENABLE;
  -----------------------------
  CREATE TABLE "XXBFM"."XXBFM_TRANSACTION_INVOICE_DTL"
    (
      "INVOICE_ID"        NUMBER,
      "SOURCE_ID"         NUMBER,
      "TRANSACTION_ID"    NUMBER,
      "INVOICE_NUM"       VARCHAR2(100),
      "INVOICE_DATE"      DATE,
      "INVOICE_VAL"       NUMBER,
      "INVOICE_DUE_DATE"  DATE,
      "INVOICE_STATUS"    NUMBER,
      "CREATED_BY"        VARCHAR2(256 BYTE) NOT NULL ENABLE,
      "CREATION_DATE"     TIMESTAMP (6) NOT NULL ENABLE,
      "LAST_UPDATED_BY"   VARCHAR2(256 BYTE) NOT NULL ENABLE,
      "LAST_UPDATE_DATE"  TIMESTAMP (6) NOT NULL ENABLE,
      "LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE),
      "VERSION"           NUMBER,
      "TENANT_ID"         NUMBER
    );
CREATE SEQUENCE XXBFM_TRANSACTION_INVC_DTL_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_TRANSACTION_INVOICE_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_INVC_DTL_PK" PRIMARY KEY ("INVOICE_ID") ENABLE;
  ALTER TABLE "XXBFM_TRANSACTION_INVOICE_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_INVC_DTL_FK1" FOREIGN KEY ("SOURCE_ID") REFERENCES "XXBFM"."XXBFM_TRANSACTION_SOURCE_DTL" ("SOURCE_ID") ENABLE;
  ALTER TABLE "XXBFM_TRANSACTION_INVOICE_DTL" ADD CONSTRAINT "XXBFM_TRANSACTION_INVC_DTL_FK2" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "XXBFM"."XXBFM_TRANSACTION_BASE" ("TRANSACTION_ID") ENABLE;

  
  ------------------------------------------------
  
  CREATE OR REPLACE VIEW XXBFM_TRANSACTION_DETAIL_V
AS
select BASE.TRANSACTION_ID, BASE.TRANSACTION_NUMBER, BASE.TYPE, BASE.CREATOR, BASE.APPROVER, DTL.TRANSACTION_DTL_ID, DTL.TRANSACTION_VERSION, DTL.TRANSACTION_DATE, DTL.BUSINESS_ENTITY_ID, DTL.ISSUING_BANK_ID,
DTL.BENEFICIARY_BANK_ID, DTL.FACILITY_TRACKER_ID, DTL.APPROVAL_STATUS
from XXBFM_TRANSACTION_DTL DTL, XXBFM_TRANSACTION_BASE BASE
where DTL.TRANSACTION_ID=BASE.TRANSACTION_ID;